[package]
name = "tatooine_script"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
config = "0.11"
log = "0.4"
simplelog = "^0.7.6"
