FAUCET_URL = "http://127.0.0.1:8080/"
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/871390641786073138/r1MugCEl_ONzzymk5ieZIaqBZz66UR6KpgqgzdnYO_jxD-tRcEZ_lYA911yqCriOHzz5"
PASSWORD = "password"